#!/usr/bin/env python3
"""Extract SRA accessions that are not yet present in existing GExA files."""
import argparse
import csv
import json
import sys
from pathlib import Path


def die(msg: str) -> None:
    raise SystemExit(f"ERROR: {msg}")


def detect_col(header, candidates, path):
    lower = {h.strip().lower(): h for h in header}
    for c in candidates:
        if c.lower() in lower:
            return lower[c.lower()]
    die(f"Could not find any of columns {candidates} in {path}. Header starts with: {header[:12]}")


def read_ids_from_csv(path: Path, candidates=("SRA", "SRR")):
    ids = []
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            die(f"CSV has no header: {path}")
        col = detect_col(reader.fieldnames, candidates, path)
        for row in reader:
            x = (row.get(col) or "").strip()
            if x:
                ids.append(x)
    return ids, col


def read_ids_from_mapping(path: Path):
    ids = []
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.DictReader(f, delimiter="\t")
        if not reader.fieldnames:
            die(f"TSV has no header: {path}")
        col = detect_col(reader.fieldnames, ("sample",), path)
        for row in reader:
            x = (row.get(col) or "").strip()
            if x:
                ids.append(x)
    return ids


def read_tmp_list(path: Path):
    rows = []
    seen = set()
    bad = []
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.reader(f, delimiter="\t")
        for lineno, row in enumerate(reader, 1):
            if not row or all(not x.strip() for x in row):
                continue
            if len(row) < 5:
                bad.append((lineno, "too_few_columns", row))
                continue
            sra, samn, bio, sample_name, lib = [x.strip() for x in row[:5]]
            if lineno == 1 and sra.lower() in {"sra", "srr", "run", "accession", "srr_or_err_or_drr"}:
                continue
            if not sra:
                bad.append((lineno, "empty_accession", row))
                continue
            lib = lib.upper()
            if lib not in {"PAIRED", "SINGLE"}:
                bad.append((lineno, f"invalid_library_type:{lib or 'EMPTY'}", row))
                continue
            if sra in seen:
                continue
            seen.add(sra)
            rows.append([sra, samn or "NA", bio or "NA", sample_name or sra, lib])
    return rows, bad


def write_rows(path: Path, rows, header=None):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        if header:
            w.writerow(header)
        w.writerows(rows)


def main():
    ap = argparse.ArgumentParser(description="Compare API_RNA-seq.py tmp_list with existing GExA matrices/QC and extract new samples.")
    ap.add_argument("--tmp-list", required=True, type=Path, help="tmp_list generated by API_RNA-seq.py; no header, 5 tab-separated columns.")
    ap.add_argument("--count", required=True, type=Path, help="Existing count matrix CSV. Must contain SRA or SRR column.")
    ap.add_argument("--tpm", required=True, type=Path, help="Existing TPM matrix CSV. Must contain SRA or SRR column.")
    ap.add_argument("--mapping-qc", required=True, type=Path, help="Existing mapping QC TSV. Must contain sample column.")
    ap.add_argument("--new-out", required=True, type=Path, help="Output TSV of new samples, no header. Used directly by mapping_script.sh.")
    ap.add_argument("--present-out", required=True, type=Path, help="Output TSV of already-present samples, no header.")
    ap.add_argument("--lib-type-out", required=True, type=Path, help="Output two-column TSV: sample and library type, derived from tmp_list.")
    ap.add_argument("--existing-ids-out", required=True, type=Path, help="Output one-column list of existing accessions.")
    ap.add_argument("--summary-json", required=True, type=Path, help="Output JSON summary.")
    ap.add_argument("--bad-rows-out", required=True, type=Path, help="Output malformed tmp_list rows.")
    args = ap.parse_args()

    for p in [args.tmp_list, args.count, args.tpm, args.mapping_qc]:
        if not p.is_file():
            die(f"Input file not found: {p}")

    count_ids, count_col = read_ids_from_csv(args.count)
    tpm_ids, tpm_col = read_ids_from_csv(args.tpm)
    mapping_ids = read_ids_from_mapping(args.mapping_qc)

    existing = set(count_ids) | set(tpm_ids) | set(mapping_ids)
    rows, bad = read_tmp_list(args.tmp_list)

    new_rows = []
    present_rows = []
    for r in rows:
        (present_rows if r[0] in existing else new_rows).append(r)

    write_rows(args.new_out, new_rows)
    write_rows(args.present_out, present_rows)
    write_rows(args.lib_type_out, [[r[0], r[4]] for r in rows], header=None)
    write_rows(args.existing_ids_out, [[x] for x in sorted(existing)], header=["sample"])
    write_rows(args.bad_rows_out, [[ln, reason, "\t".join(row)] for ln, reason, row in bad], header=["line", "reason", "raw_row"])

    summary = {
        "candidate_samples": len(rows),
        "bad_tmp_list_rows": len(bad),
        "existing_unique_samples": len(existing),
        "existing_count_samples": len(count_ids),
        "existing_tpm_samples": len(tpm_ids),
        "existing_mapping_qc_samples": len(mapping_ids),
        "count_accession_column": count_col,
        "tpm_accession_column": tpm_col,
        "already_present_samples": len(present_rows),
        "new_samples": len(new_rows),
        "new_samples_preview": [r[0] for r in new_rows[:50]],
    }
    args.summary_json.parent.mkdir(parents=True, exist_ok=True)
    args.summary_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
