#!/usr/bin/env python3
"""Filter count and mapping QC files to match the sample order of a filtered TPM matrix."""
import argparse
import csv
import shutil
import sys
from pathlib import Path
import pandas as pd

csv.field_size_limit(sys.maxsize)


def die(msg):
    raise SystemExit(f"ERROR: {msg}")


def get_csv_header(path: Path):
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.reader(f)
        header = next(reader, None)
    if not header:
        die(f"CSV has no header: {path}")
    return header


def detect_sra_col(header):
    for c in ("SRA", "SRR"):
        if c in header:
            return c
    lower = {h.lower(): h for h in header}
    for c in ("sra", "srr"):
        if c in lower:
            return lower[c]
    die(f"Could not find SRA/SRR column. Header starts with: {header[:12]}")


def read_sra_order(path: Path):
    header = get_csv_header(path)
    col = detect_sra_col(header)
    order = []
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.DictReader(f)
        for row in reader:
            sid = (row.get(col) or "").strip()
            if sid:
                order.append(sid)
    if len(order) != len(set(order)):
        dups = [x for x in order if order.count(x) > 1]
        die("Filtered TPM contains duplicated SRA/SRR IDs: " + ", ".join(sorted(set(dups))[:20]))
    return order, col


def read_low_removed(path: Path):
    if not path.is_file():
        return []
    rows = []
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.reader(f, delimiter="\t")
        for i, row in enumerate(reader, 1):
            if not row:
                continue
            # check_sample.sh writes first two metadata columns; SRA is normally the second column.
            if i == 1 and any(x.lower() in {"sra", "srr", "sample"} for x in row):
                continue
            sid = row[1].strip() if len(row) > 1 else row[0].strip()
            if sid:
                rows.append(sid)
    return rows


def sync_count(count_in: Path, count_out: Path, target_order, sra_col):
    rows_by_id = {}
    header = get_csv_header(count_in)
    if sra_col not in header:
        sra_col = detect_sra_col(header)
    with count_in.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.DictReader(f)
        for row in reader:
            sid = (row.get(sra_col) or "").strip()
            if sid:
                rows_by_id[sid] = row
    missing = [sid for sid in target_order if sid not in rows_by_id]
    if missing:
        die("Samples in filtered TPM are missing from count matrix: " + ", ".join(missing[:20]))
    count_out.parent.mkdir(parents=True, exist_ok=True)
    with count_out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=header, lineterminator="\n")
        writer.writeheader()
        for sid in target_order:
            writer.writerow(rows_by_id[sid])


def sync_mapping(mapping_in: Path, mapping_out: Path, target_order):
    m = pd.read_csv(mapping_in, sep="\t", dtype=str)
    if "sample" not in m.columns:
        die("Mapping QC must contain a sample column")
    if m["sample"].duplicated().any():
        d = m.loc[m["sample"].duplicated(), "sample"].head(20).tolist()
        die("Mapping QC contains duplicated sample IDs: " + ", ".join(d))
    m = m.set_index("sample", drop=False)
    missing = [sid for sid in target_order if sid not in m.index]
    if missing:
        die("Samples in filtered TPM are missing from mapping QC: " + ", ".join(missing[:20]))
    out = m.loc[target_order].reset_index(drop=True)
    mapping_out.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(mapping_out, sep="\t", index=False)


def main():
    ap = argparse.ArgumentParser(description="Remove low-TPM samples from count/mapping files and force count/mapping order to match the filtered TPM matrix.")
    ap.add_argument("--filtered-tpm", required=True, type=Path, help="TPM CSV after check_sample.sh filtering.")
    ap.add_argument("--count", required=True, type=Path, help="Updated count matrix before low-TPM filtering.")
    ap.add_argument("--mapping-qc", required=True, type=Path, help="Updated mapping QC before low-TPM filtering.")
    ap.add_argument("--low-list", required=True, type=Path, help="lowTPM list generated by check_sample.sh.")
    ap.add_argument("--count-out", required=True, type=Path, help="Output count matrix with same samples/order as filtered TPM.")
    ap.add_argument("--mapping-out", required=True, type=Path, help="Output mapping QC with same samples/order as filtered TPM.")
    ap.add_argument("--removed-out", required=True, type=Path, help="Output removed sample list, one sample per line.")
    ap.add_argument("--report", required=True, type=Path, help="Output text report.")
    args = ap.parse_args()

    target_order, sra_col = read_sra_order(args.filtered_tpm)
    removed = read_low_removed(args.low_list)
    args.removed_out.parent.mkdir(parents=True, exist_ok=True)
    with args.removed_out.open("w", encoding="utf-8") as f:
        f.write("sample\n")
        for x in removed:
            f.write(f"{x}\n")
    sync_count(args.count, args.count_out, target_order, sra_col)
    sync_mapping(args.mapping_qc, args.mapping_out, target_order)
    report = (
        f"filtered_tpm_samples\t{len(target_order)}\n"
        f"lowTPM_removed_samples\t{len(removed)}\n"
        f"count_output\t{args.count_out}\n"
        f"mapping_output\t{args.mapping_out}\n"
    )
    args.report.write_text(report, encoding="utf-8")
    print(report, end="")


if __name__ == "__main__":
    main()
