#!/usr/bin/env python3
"""Build a mapping QC TSV from STAR Log.final.out files and mapping_script metadata."""
import argparse
import csv
import re
from pathlib import Path


def die(msg: str) -> None:
    raise SystemExit(f"ERROR: {msg}")


def sanitize_code(sample_name: str) -> str:
    x = sample_name.strip() if sample_name else ""
    x = re.sub(r"\s+", "_", x)
    return x


def parse_star_log(path: Path):
    vals = {}
    with path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if "|" not in line:
                continue
            key, val = [x.strip() for x in line.split("|", 1)]
            vals[key] = val

    def int_field(key, default=0):
        v = vals.get(key, str(default)).replace(",", "").strip()
        m = re.search(r"[-+]?\d+", v)
        return int(m.group(0)) if m else default

    total = int_field("Number of input reads")
    unique = int_field("Uniquely mapped reads number")
    multi = int_field("Number of reads mapped to multiple loci")
    too_many = int_field("Number of reads mapped to too many loci")
    mapped = unique + multi + too_many
    mapping_rate = (mapped / total * 100.0) if total else 0.0
    unique_rate = (unique / total * 100.0) if total else 0.0
    return total, mapped, mapping_rate, unique, unique_rate


def read_metadata(path: Path):
    rows = []
    with path.open("r", newline="", encoding="utf-8-sig", errors="replace") as f:
        reader = csv.DictReader(f, delimiter="\t")
        required = {"srr", "sample_name", "lib"}
        if not reader.fieldnames:
            die(f"Metadata file has no header: {path}")
        missing = required - set(reader.fieldnames)
        if missing:
            die(f"Metadata file is missing columns {sorted(missing)}: {path}")
        for row in reader:
            if (row.get("srr") or "").strip():
                rows.append(row)
    return rows


def main():
    ap = argparse.ArgumentParser(description="Extract total/mapped/unique mapping statistics from STAR Log.final.out files.")
    ap.add_argument("--metadata", required=True, type=Path, help="prefix_metadata.tsv generated by mapping_script.sh.")
    ap.add_argument("--search-dir", required=True, type=Path, help="Directory containing STAR logs, usually the mapping working directory.")
    ap.add_argument("--out", required=True, type=Path, help="Output mapping QC TSV without assigned-gene proportion.")
    ap.add_argument("--failed-out", required=True, type=Path, help="Output TSV listing samples whose STAR log was not found or could not be parsed.")
    ap.add_argument("--digits", type=int, default=2, help="Decimal digits for percentage columns. Default: 2.")
    args = ap.parse_args()

    if not args.metadata.is_file():
        die(f"Metadata file not found: {args.metadata}")
    if not args.search_dir.is_dir():
        die(f"Search directory not found: {args.search_dir}")

    rows = read_metadata(args.metadata)
    out_rows = []
    failed = []
    for r in rows:
        srr = r["srr"].strip()
        sample_name = (r.get("sample_name") or srr).strip() or srr
        code = sanitize_code(sample_name)
        candidates = [args.search_dir / f"{code}_Log.final.out", args.search_dir / "logs" / f"{code}_Log.final.out"]
        # Fallback: sometimes code is SRR or sanitized differently.
        candidates += list(args.search_dir.glob(f"*{srr}*Log.final.out"))
        candidates += list((args.search_dir / "logs").glob(f"*{srr}*Log.final.out")) if (args.search_dir / "logs").is_dir() else []
        log = next((p for p in candidates if p.is_file()), None)
        if log is None:
            failed.append([srr, sample_name, code, "STAR_Log.final.out_not_found"])
            continue
        try:
            total, mapped, mrate, unique, urate = parse_star_log(log)
            if total <= 0:
                raise ValueError("Number of input reads is zero or missing")
        except Exception as e:
            failed.append([srr, sample_name, code, f"parse_failed:{e}"])
            continue
        out_rows.append([
            srr,
            str(total),
            str(mapped),
            f"{mrate:.{args.digits}f}",
            str(unique),
            f"{urate:.{args.digits}f}",
        ])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        w.writerow(["sample", "total_reads", "mapped_reads", "mapping_rate", "uniquely_mapped_reads", "unique_mapping_rate"])
        w.writerows(out_rows)

    args.failed_out.parent.mkdir(parents=True, exist_ok=True)
    with args.failed_out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        w.writerow(["sample", "sample_name", "code", "reason"])
        w.writerows(failed)

    print(f"Wrote: {args.out}")
    print(f"Parsed STAR logs: {len(out_rows)}")
    print(f"Failed samples: {len(failed)}")


if __name__ == "__main__":
    main()
