#!/usr/bin/env bash
set -euo pipefail

show_help() {
cat <<'EOF'
update_gexa.sh - One-command updater for a single species in Grass Expression Atlas (GExA)

This wrapper reuses the existing GExA RNA-seq scripts and adds safety checks,
resume support, matrix merging, QC synchronization, metadata standardization, and
static shard generation. Existing input files are never overwritten.

Usage:
  bash update_gexa.sh \
    --species "pearl millet" "Cenchrus americanus" "Pennisetum glaucum" \
    --prefix PM_Tift \
    --count Pearl_millet_count_data_cv_Tift.csv \
    --tpm Pearl_millet_TPM_data_cv_Tift.csv \
    --mapping-qc PM_Tift_STAR_mapping_w_assigned.tsv \
    --star-index /path/to/STAR_index \
    --gff /path/to/annotation.gff3 \
    --workdir gexa_update_2026_06 \
    --outdir updated_GExA \
    --standardize-script standardize_metadata_pearl_millet.py

Required arguments:
  --species NAME [NAME ...]
      One or more species names passed to API_RNA-seq.py. Values are read until
      the next option beginning with '--'.
  --prefix PREFIX
      Existing GExA species prefix, for example PM_Tift. New mapping output will
      use new_PREFIX so the existing files are not touched.
  --count FILE
      Existing count matrix CSV. The left 10 columns are metadata; the SRA/SRR
      accession column must be named SRA or SRR.
  --tpm FILE
      Existing TPM matrix CSV. The left 10 columns are metadata; the SRA/SRR
      accession column must be named SRA or SRR.
  --mapping-qc FILE
      Existing STAR mapping QC TSV. Must contain a sample column.
  --star-index DIR
      STAR genome index directory.
  --gff FILE
      GFF3 annotation used by featureCounts.
  --workdir DIR
      Working directory for API output, mapping output, logs, and intermediate files.
  --outdir DIR
      Output directory for updated matrices, mapping QC, standardized files, and shards.
  --standardize-script FILE
      Metadata standardization script. The script must accept two positional arguments:
        python3 SCRIPT input.csv output.csv

Optional arguments:
  --scripts-dir DIR
      Directory containing the existing pipeline scripts. Default: the parent
      scripts/ directory when this wrapper is under scripts/GExA_update_script,
      otherwise the current directory.
      The wrapper accepts exact names such as API_RNA-seq.py and also files with
      suffixes such as API_RNA-seq(4).py.
  --lib-type FILE
      Optional two-column TSV with sample and SINGLE/PAIRED for existing samples.
      This is useful if some existing mapping-QC samples are not returned by the
      current API_RNA-seq.py search. The API-derived library types are appended.
  --metadata-cols N
      Number of metadata columns at the left side of count/TPM matrices. Default: 10.
  --allow-new-genes
      Append genes found only in the new matrix. Default is safer: keep the existing
      gene list/order and exclude extra new genes with a warning in the JSON report.
  --dry-run
      Run API search and sample comparison only. Do not run mapping and do not
      create merged/updated output files.
  --force
      Re-run steps even if intermediate files already exist. Without --force, the
      wrapper reuses tmp_list, new matrices, and other intermediate files when possible.
  -h, --help
      Show this help message and exit.

Main outputs:
  OUTDIR/*.updated.csv
      Updated count and TPM matrices before low-TPM filtering.
  OUTDIR/*.standardized.csv
      Final standardized count and TPM matrices after low-TPM filtering and metadata cleanup.
  OUTDIR/*mapping*.tsv
      Updated mapping QC with assigned-gene proportion and final synchronized mapping QC.
  OUTDIR/out_sharded/
      Static files generated by preprocess_shard.py: meta.tsv, gene_index.tsv,
      manifest.json, and shards/shard_XXX.bin.
  WORKDIR/update_gexa.log
      Full execution log.

Resume behavior:
  - If WORKDIR/api/tmp_list exists, API search is reused unless --force is given.
  - If new_PREFIX_count_matrix.csv/new_PREFIX_TPM_matrix.csv already contain some
    SRA IDs, those samples are removed from the pending list and are not remapped.
  - Failed or skipped samples are summarized in WORKDIR/failed_samples.tsv.

EOF
}

SPECIES=()
PREFIX=""
COUNT=""
TPM=""
MAPPING_QC=""
STAR_INDEX=""
GFF=""
WORKDIR=""
OUTDIR=""
SCRIPTS_DIR=""
STANDARDIZE_SCRIPT_NAME=""
LIB_TYPE_FILE=""
METADATA_COLS=10
ALLOW_NEW_GENES=0
DRY_RUN=0
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --species)
      shift
      SPECIES=()
      while [[ $# -gt 0 && "$1" != --* ]]; do
        SPECIES+=("$1")
        shift
      done
      ;;
    --prefix) PREFIX=${2:?Missing value for --prefix}; shift 2 ;;
    --count) COUNT=${2:?Missing value for --count}; shift 2 ;;
    --tpm) TPM=${2:?Missing value for --tpm}; shift 2 ;;
    --mapping-qc) MAPPING_QC=${2:?Missing value for --mapping-qc}; shift 2 ;;
    --star-index) STAR_INDEX=${2:?Missing value for --star-index}; shift 2 ;;
    --gff) GFF=${2:?Missing value for --gff}; shift 2 ;;
    --workdir) WORKDIR=${2:?Missing value for --workdir}; shift 2 ;;
    --outdir) OUTDIR=${2:?Missing value for --outdir}; shift 2 ;;
    --scripts-dir) SCRIPTS_DIR=${2:?Missing value for --scripts-dir}; shift 2 ;;
    --lib-type) LIB_TYPE_FILE=${2:?Missing value for --lib-type}; shift 2 ;;
    --metadata-cols) METADATA_COLS=${2:?Missing value for --metadata-cols}; shift 2 ;;
    --standardize-script) STANDARDIZE_SCRIPT_NAME=${2:?Missing value for --standardize-script}; shift 2 ;;
    --allow-new-genes) ALLOW_NEW_GENES=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) show_help; exit 0 ;;
    *) echo "ERROR: Unknown argument: $1" >&2; show_help >&2; exit 1 ;;
  esac
done

if [[ ${#SPECIES[@]} -eq 0 || -z "$PREFIX" || -z "$COUNT" || -z "$TPM" || -z "$MAPPING_QC" || -z "$STAR_INDEX" || -z "$GFF" || -z "$WORKDIR" || -z "$OUTDIR" || -z "$STANDARDIZE_SCRIPT_NAME" ]]; then
  echo "ERROR: Missing required arguments." >&2
  show_help >&2
  exit 1
fi

abs_path() {
  python3 - "$1" <<'PY'
from pathlib import Path
import sys
print(Path(sys.argv[1]).expanduser().resolve())
PY
}

COUNT=$(abs_path "$COUNT")
TPM=$(abs_path "$TPM")
MAPPING_QC=$(abs_path "$MAPPING_QC")
STAR_INDEX=$(abs_path "$STAR_INDEX")
GFF=$(abs_path "$GFF")
WORKDIR=$(abs_path "$WORKDIR")
OUTDIR=$(abs_path "$OUTDIR")
WRAPPER_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if [[ -z "$SCRIPTS_DIR" ]]; then
  if [[ -f "$WRAPPER_DIR/../API_RNA-seq.py" ]]; then
    SCRIPTS_DIR="$WRAPPER_DIR/.."
  else
    SCRIPTS_DIR="."
  fi
fi
SCRIPTS_DIR=$(abs_path "$SCRIPTS_DIR")
if [[ -n "$LIB_TYPE_FILE" ]]; then LIB_TYPE_FILE=$(abs_path "$LIB_TYPE_FILE"); fi

mkdir -p "$WORKDIR" "$OUTDIR"
LOG="$WORKDIR/update_gexa.log"
exec > >(tee -a "$LOG") 2>&1

step() {
  echo
  echo "===== [$1] $(date '+%Y-%m-%d %H:%M:%S') ====="
}

finish_step() {
  echo "===== [DONE] $1 $(date '+%Y-%m-%d %H:%M:%S') ====="
}

require_file() {
  local p="$1"
  local label="$2"
  if [[ ! -f "$p" ]]; then
    echo "ERROR: $label not found: $p" >&2
    exit 1
  fi
}

require_dir() {
  local p="$1"
  local label="$2"
  if [[ ! -d "$p" ]]; then
    echo "ERROR: $label not found or not a directory: $p" >&2
    exit 1
  fi
}

resolve_script() {
  local wanted="$1"
  local base ext matches
  if [[ -f "$SCRIPTS_DIR/$wanted" ]]; then
    echo "$SCRIPTS_DIR/$wanted"
    return 0
  fi
  base="${wanted%.*}"
  ext="${wanted##*.}"
  shopt -s nullglob
  matches=("$SCRIPTS_DIR"/"$base"*."$ext")
  shopt -u nullglob
  if [[ ${#matches[@]} -gt 0 ]]; then
    echo "${matches[0]}"
    return 0
  fi
  echo "ERROR: Required script not found in --scripts-dir: $wanted" >&2
  exit 1
}

check_command() {
  local c="$1"
  if ! command -v "$c" >/dev/null 2>&1; then
    echo "ERROR: Required command not found in PATH: $c" >&2
    exit 1
  fi
}

make_out_name() {
  local input="$1"
  local tag="$2"
  local b stem ext
  b=$(basename "$input")
  if [[ "$b" == *.* ]]; then
    stem="${b%.*}"
    ext="${b##*.}"
    echo "$OUTDIR/${stem}.${tag}.${ext}"
  else
    echo "$OUTDIR/${b}.${tag}"
  fi
}

collect_logs() {
  local src="$1"
  local dst="$2"
  mkdir -p "$dst"
  shopt -s nullglob
  local patterns=(
    "*.Log.final.out" "*.Log.out" "*.Log.progress.out"
    "*fastp.html" "*fastp.json" "fastp.html" "fastp.json"
    "*.summary" "*_counts.txt.summary"
    "Download_failed_list.txt" "samples_too_small_size.txt" "STAR_failed*" "failed_samples.tsv"
  )
  local p f
  for p in "${patterns[@]}"; do
    for f in "$src"/$p; do
      [[ -e "$f" ]] || continue
      mv -f "$f" "$dst/" || true
    done
  done
  shopt -u nullglob
}

step "Dependency and input checks"
require_file "$COUNT" "count matrix"
require_file "$TPM" "TPM matrix"
require_file "$MAPPING_QC" "mapping QC TSV"
require_file "$GFF" "GFF3 annotation"
require_dir "$STAR_INDEX" "STAR genome index"
require_dir "$SCRIPTS_DIR" "scripts directory"
if [[ -n "$LIB_TYPE_FILE" ]]; then require_file "$LIB_TYPE_FILE" "library type TSV"; fi

for c in python3 bash awk sed sort comm STAR fastp samtools featureCounts prefetch fasterq-dump; do
  check_command "$c"
done
if ! command -v aria2c >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
  echo "ERROR: Either aria2c or wget is required for SRA download." >&2
  exit 1
fi
if ! command -v aria2c >/dev/null 2>&1; then
  echo "[WARN] aria2c was not found. mapping_script.sh primarily tries aria2c and then falls back to wget for some download paths. Installing aria2c is recommended."
fi
python3 - <<'PY'
import importlib.util, sys
for mod in ["pandas", "bs4"]:
    if importlib.util.find_spec(mod) is None:
        raise SystemExit(f"ERROR: Required Python module is not installed: {mod}")
print("Python modules OK: pandas, bs4")
PY

API_SCRIPT=$(resolve_script "API_RNA-seq.py")
MAPPING_SCRIPT=$(resolve_script "mapping_script.sh")
FIND_SAMN_SCRIPT=$(resolve_script "findSAMN_info.py")
CHECK_SAMPLE_SCRIPT=$(resolve_script "check_sample.sh")
STD_SCRIPT=$(resolve_script "$STANDARDIZE_SCRIPT_NAME")
ADD_ASSIGNED_SCRIPT="$WRAPPER_DIR/add_assigned_gene_proportion.py"
PREPROCESS_SHARD_SCRIPT=$(resolve_script "preprocess_shard.py")
GET_EXPT_SCRIPT=$(resolve_script "get_expt_from_srr.py")
COUNT_TO_TPM_SCRIPT=$(resolve_script "Count_to_TPM.py")

for h in add_assigned_gene_proportion.py extract_new_sra.py merge_gexa_matrices.py star_log_to_mapping_qc.py merge_mapping_qc.py filter_and_sync_samples.py validate_gexa_update.py normalize_sra_column.py; do
  require_file "$WRAPPER_DIR/$h" "helper script $h"
done
finish_step "Dependency and input checks"

API_DIR="$WORKDIR/api"
MAPPING_DIR="$WORKDIR/mapping"
LOG_DIR="$WORKDIR/logs"
REPORT_DIR="$WORKDIR/reports"
mkdir -p "$API_DIR" "$MAPPING_DIR" "$LOG_DIR" "$REPORT_DIR"

step "API_RNA-seq.py search"
TMP_LIST="$API_DIR/tmp_list"
if [[ "$FORCE" -eq 1 || ! -s "$TMP_LIST" ]]; then
  rm -f "$API_DIR"/tmp "$API_DIR"/tmp_2 "$API_DIR"/*_tmp "$TMP_LIST"
  (cd "$API_DIR" && python3 "$API_SCRIPT" "${SPECIES[@]}")
else
  echo "Reusing existing API tmp_list: $TMP_LIST"
fi
require_file "$TMP_LIST" "API tmp_list"
finish_step "API_RNA-seq.py search"

step "Extract new SRA samples"
NEW_SAMPLES="$WORKDIR/new_samples.tsv"
ALREADY_PRESENT="$WORKDIR/already_present_samples.tsv"
LIB_TYPE_API="$WORKDIR/library_type_from_api.tsv"
EXISTING_IDS="$WORKDIR/existing_samples.tsv"
SUMMARY_JSON="$WORKDIR/sample_selection_summary.json"
BAD_TMP_ROWS="$WORKDIR/tmp_list_bad_rows.tsv"
python3 "$WRAPPER_DIR/extract_new_sra.py" \
  --tmp-list "$TMP_LIST" \
  --count "$COUNT" \
  --tpm "$TPM" \
  --mapping-qc "$MAPPING_QC" \
  --new-out "$NEW_SAMPLES" \
  --present-out "$ALREADY_PRESENT" \
  --lib-type-out "$LIB_TYPE_API" \
  --existing-ids-out "$EXISTING_IDS" \
  --summary-json "$SUMMARY_JSON" \
  --bad-rows-out "$BAD_TMP_ROWS"
NEW_N=$(python3 - "$SUMMARY_JSON" <<'PY'
import json, sys
print(json.load(open(sys.argv[1]))['new_samples'])
PY
)
CAND_N=$(python3 - "$SUMMARY_JSON" <<'PY'
import json, sys
print(json.load(open(sys.argv[1]))['candidate_samples'])
PY
)
PRESENT_N=$(python3 - "$SUMMARY_JSON" <<'PY'
import json, sys
print(json.load(open(sys.argv[1]))['already_present_samples'])
PY
)
finish_step "Extract new SRA samples"

if [[ "$DRY_RUN" -eq 1 ]]; then
  step "Dry run summary"
  echo "Candidate RNA-seq samples from API_RNA-seq.py: $CAND_N"
  echo "Already present samples: $PRESENT_N"
  echo "New samples to add: $NEW_N"
  echo
  echo "New sample list: $NEW_SAMPLES"
  if [[ -s "$NEW_SAMPLES" ]]; then
    cat "$NEW_SAMPLES"
  fi
  echo
  echo "Commands that would be executed after dry-run:"
  echo "  bash mapping_script.sh new_samples.tsv new_${PREFIX} '$STAR_INDEX' '$GFF'"
  echo "  python3 merge_gexa_matrices.py --existing '$COUNT' --new '${MAPPING_DIR}/new_${PREFIX}_count_matrix.csv' ..."
  echo "  python3 merge_gexa_matrices.py --existing '$TPM' --new '${MAPPING_DIR}/new_${PREFIX}_TPM_matrix.csv' ..."
  echo "  python3 star_log_to_mapping_qc.py ..."
  echo "  python3 add_assigned_gene_proportion.py ..."
  echo "  bash check_sample.sh updated_TPM.csv ..."
  echo "  python3 '$STD_SCRIPT' filtered_TPM.csv standardized_TPM.csv ..."
  echo "  python3 preprocess_shard.py final_standardized_TPM.csv '$OUTDIR/out_sharded'"
  echo
  echo "Dry run finished. No mapping or output-file update was performed."
  exit 0
fi

if [[ "$NEW_N" -eq 0 ]]; then
  echo "No new RNA-seq samples were found. Existing GExA files were not modified."
  exit 0
fi

step "Prepare runtime mapping directory"
cp -f "$MAPPING_SCRIPT" "$MAPPING_DIR/mapping_script.sh"
cp -f "$FIND_SAMN_SCRIPT" "$MAPPING_DIR/findSAMN_info.py"
cp -f "$GET_EXPT_SCRIPT" "$MAPPING_DIR/get_expt_from_srr.py"
cp -f "$COUNT_TO_TPM_SCRIPT" "$MAPPING_DIR/Count_to_TPM.py"
chmod +x "$MAPPING_DIR/mapping_script.sh"
# Runtime patch only on the copied mapping script: use python3 and preserve per-sample fastp logs when the exact fastp blocks match.
python3 - "$MAPPING_DIR/mapping_script.sh" <<'PY'
from pathlib import Path
import sys
p = Path(sys.argv[1])
s = p.read_text(encoding="utf-8", errors="replace")
s = s.replace("python findSAMN_info.py", "python3 findSAMN_info.py")
s = s.replace("python get_expt_from_srr.py", "python3 get_expt_from_srr.py")
s = s.replace("python Count_to_TPM.py", "python3 Count_to_TPM.py")
s = s.replace('fastp -i "${code}_raw_R1.fastq" -I "${code}_raw_R2.fastq" \\\n              -o "${code}_R1.fastq" -O "${code}_R2.fastq"',
              'fastp -i "${code}_raw_R1.fastq" -I "${code}_raw_R2.fastq" \\\n              -o "${code}_R1.fastq" -O "${code}_R2.fastq" \\\n              -h "${code}_fastp.html" -j "${code}_fastp.json"')
s = s.replace('fastp -i "${code}_raw_R.fastq" -o "${code}_R.fastq"',
              'fastp -i "${code}_raw_R.fastq" -o "${code}_R.fastq" \\\n              -h "${code}_fastp.html" -j "${code}_fastp.json"')
s = s.replace('mv "${sra}.sra" sra\n    mv ${sra} sra', 'mkdir -p sra\n    mv "${sra}.sra" sra 2>/dev/null || true\n    mv "${sra}" sra 2>/dev/null || true')
p.write_text(s, encoding="utf-8")
PY
finish_step "Prepare runtime mapping directory"

step "Build pending sample list for resume"
NEW_PREFIX="new_${PREFIX}"
NEW_COUNT_MATRIX="$MAPPING_DIR/${NEW_PREFIX}_count_matrix.csv"
NEW_TPM_MATRIX="$MAPPING_DIR/${NEW_PREFIX}_TPM_matrix.csv"
PENDING_SAMPLES="$MAPPING_DIR/pending_new_samples.tsv"
cp -f "$NEW_SAMPLES" "$MAPPING_DIR/new_samples.tsv"
if [[ "$FORCE" -eq 1 ]]; then
  rm -f "$NEW_COUNT_MATRIX" "$NEW_TPM_MATRIX" "$MAPPING_DIR/${NEW_PREFIX}_metadata.tsv"
fi
python3 - "$MAPPING_DIR/new_samples.tsv" "$NEW_COUNT_MATRIX" "$PENDING_SAMPLES" <<'PY'
import csv, sys
from pathlib import Path
new_samples = Path(sys.argv[1])
existing_new_matrix = Path(sys.argv[2])
pending = Path(sys.argv[3])
processed = set()
if existing_new_matrix.is_file() and existing_new_matrix.stat().st_size > 0:
    with existing_new_matrix.open(newline='', encoding='utf-8-sig', errors='replace') as f:
        reader = csv.DictReader(f)
        if reader.fieldnames:
            col = 'SRA' if 'SRA' in reader.fieldnames else ('SRR' if 'SRR' in reader.fieldnames else None)
            if col:
                for row in reader:
                    if row.get(col): processed.add(row[col].strip())
with new_samples.open(newline='', encoding='utf-8-sig', errors='replace') as fin, pending.open('w', newline='', encoding='utf-8') as fout:
    r = csv.reader(fin, delimiter='\t')
    w = csv.writer(fout, delimiter='\t', lineterminator='\n')
    kept = 0
    skipped = 0
    for row in r:
        if not row: continue
        sid = row[0].strip()
        if sid in processed:
            skipped += 1
            continue
        w.writerow(row)
        kept += 1
print(f"Previously processed new samples detected: {len(processed)}")
print(f"Pending samples for mapping: {kept}")
print(f"Skipped already processed samples from pending list: {skipped}")
PY
PENDING_N=$(awk 'NF>0{n++} END{print n+0}' "$PENDING_SAMPLES")
finish_step "Build pending sample list for resume"

step "Run mapping_script.sh for pending samples"
if [[ "$PENDING_N" -gt 0 ]]; then
  (cd "$MAPPING_DIR" && bash ./mapping_script.sh pending_new_samples.tsv "$NEW_PREFIX" "$STAR_INDEX" "$GFF")
else
  echo "No pending samples. Reusing existing new matrices in $MAPPING_DIR"
fi
require_file "$NEW_COUNT_MATRIX" "new count matrix generated by mapping_script.sh"
require_file "$NEW_TPM_MATRIX" "new TPM matrix generated by mapping_script.sh"
finish_step "Run mapping_script.sh for pending samples"

step "Build failed sample summary and mapping QC from STAR logs"
NEW_METADATA="$MAPPING_DIR/${NEW_PREFIX}_metadata.tsv"
NEW_MAPPING_QC_BASE="$WORKDIR/new_mapping_qc.no_assigned.tsv"
STAR_PARSE_FAILED="$WORKDIR/star_log_parse_failed.tsv"
python3 "$WRAPPER_DIR/star_log_to_mapping_qc.py" \
  --metadata "$NEW_METADATA" \
  --search-dir "$MAPPING_DIR" \
  --out "$NEW_MAPPING_QC_BASE" \
  --failed-out "$STAR_PARSE_FAILED"
FAILED_SUMMARY="$WORKDIR/failed_samples.tsv"
{
  echo -e "source\tsample\tdetail"
  if [[ -f "$MAPPING_DIR/Download_failed_list.txt" ]]; then awk 'BEGIN{FS=OFS="\t"} NF{print "Download_or_STAR", $1, $0}' "$MAPPING_DIR/Download_failed_list.txt"; fi
  if [[ -f "$MAPPING_DIR/samples_too_small_size.txt" ]]; then awk 'BEGIN{FS=OFS="\t"} NF{print "Too_small_FASTQ", $1, $0}' "$MAPPING_DIR/samples_too_small_size.txt"; fi
  if [[ -f "$STAR_PARSE_FAILED" ]]; then awk 'BEGIN{FS=OFS="\t"} NR>1 && NF{print "STAR_log_parse", $1, $0}' "$STAR_PARSE_FAILED"; fi
} > "$FAILED_SUMMARY"
collect_logs "$MAPPING_DIR" "$LOG_DIR"
finish_step "Build failed sample summary and mapping QC from STAR logs"

step "Back up original inputs"
BACKUP_DIR="$OUTDIR/backup"
mkdir -p "$BACKUP_DIR"
STAMP=$(date '+%Y%m%d_%H%M%S')
cp -p "$COUNT" "$BACKUP_DIR/$(basename "$COUNT").${STAMP}.bak"
cp -p "$TPM" "$BACKUP_DIR/$(basename "$TPM").${STAMP}.bak"
cp -p "$MAPPING_QC" "$BACKUP_DIR/$(basename "$MAPPING_QC").${STAMP}.bak"
finish_step "Back up original inputs"

step "Merge count and TPM matrices"
COUNT_UPDATED=$(make_out_name "$COUNT" "updated")
TPM_UPDATED=$(make_out_name "$TPM" "updated")
MERGE_COUNT_REPORT="$REPORT_DIR/merge_count_report.json"
MERGE_TPM_REPORT="$REPORT_DIR/merge_tpm_report.json"
MERGE_ARGS=()
if [[ "$ALLOW_NEW_GENES" -eq 1 ]]; then MERGE_ARGS+=(--allow-new-genes); fi
python3 "$WRAPPER_DIR/merge_gexa_matrices.py" \
  --existing "$COUNT" \
  --new "$NEW_COUNT_MATRIX" \
  --out "$COUNT_UPDATED" \
  --report "$MERGE_COUNT_REPORT" \
  --matrix-type count \
  --metadata-cols "$METADATA_COLS" \
  "${MERGE_ARGS[@]}"
python3 "$WRAPPER_DIR/merge_gexa_matrices.py" \
  --existing "$TPM" \
  --new "$NEW_TPM_MATRIX" \
  --out "$TPM_UPDATED" \
  --report "$MERGE_TPM_REPORT" \
  --matrix-type tpm \
  --metadata-cols "$METADATA_COLS" \
  "${MERGE_ARGS[@]}"
finish_step "Merge count and TPM matrices"

step "Update mapping QC and assigned-gene proportion"
MAPPING_MERGED_NO_ASSIGNED="$WORKDIR/mapping_qc.updated.no_assigned.tsv"
MAPPING_MERGE_REPORT="$REPORT_DIR/merge_mapping_qc_report.tsv"
python3 "$WRAPPER_DIR/merge_mapping_qc.py" \
  --existing "$MAPPING_QC" \
  --new "$NEW_MAPPING_QC_BASE" \
  --out "$MAPPING_MERGED_NO_ASSIGNED" \
  --report "$MAPPING_MERGE_REPORT"
LIB_TYPE_ALL="$WORKDIR/library_type_all.tsv"
if [[ -n "$LIB_TYPE_FILE" ]]; then
  cat "$LIB_TYPE_FILE" "$LIB_TYPE_API" > "$WORKDIR/library_type_concat.tsv"
else
  cp -f "$LIB_TYPE_API" "$WORKDIR/library_type_concat.tsv"
fi
awk 'BEGIN{FS=OFS="\t"} NF>=2{t=toupper($2); if($1!="" && (t=="SINGLE" || t=="PAIRED")) print $1,t}' "$WORKDIR/library_type_concat.tsv" | sort -u > "$LIB_TYPE_ALL"
MAPPING_UPDATED=$(make_out_name "$MAPPING_QC" "updated")
COUNT_FOR_ASSIGNED="$WORKDIR/count_for_assigned.SRA.csv"
python3 "$WRAPPER_DIR/normalize_sra_column.py" --input "$COUNT_UPDATED" --output "$COUNT_FOR_ASSIGNED"
python3 "$ADD_ASSIGNED_SCRIPT" \
  --counts "$COUNT_FOR_ASSIGNED" \
  --mapping "$MAPPING_MERGED_NO_ASSIGNED" \
  --lib-type "$LIB_TYPE_ALL" \
  --out "$MAPPING_UPDATED" \
  --metadata-cols "$METADATA_COLS"
finish_step "Update mapping QC and assigned-gene proportion"

step "Run check_sample.sh and synchronize low-TPM removals"
CHECK_DIR="$WORKDIR/check_sample"
mkdir -p "$CHECK_DIR"
CHECK_PREFIX="$CHECK_DIR/$(basename "${TPM_UPDATED%.csv}")"
bash "$CHECK_SAMPLE_SCRIPT" "$TPM_UPDATED" "$CHECK_PREFIX"
TPM_FILTERED_WORK="${CHECK_PREFIX}.filtered.csv"
LOW_TPM_WORK="${CHECK_PREFIX}.lowTPM_samples.tsv"
require_file "$TPM_FILTERED_WORK" "check_sample.sh filtered TPM output"
COUNT_FILTERED=$(make_out_name "$COUNT" "updated.filtered")
TPM_FILTERED=$(make_out_name "$TPM" "updated.filtered")
MAPPING_FILTERED=$(make_out_name "$MAPPING_QC" "updated.filtered")
cp -f "$TPM_FILTERED_WORK" "$TPM_FILTERED"
python3 "$WRAPPER_DIR/filter_and_sync_samples.py" \
  --filtered-tpm "$TPM_FILTERED" \
  --count "$COUNT_UPDATED" \
  --mapping-qc "$MAPPING_UPDATED" \
  --low-list "$LOW_TPM_WORK" \
  --count-out "$COUNT_FILTERED" \
  --mapping-out "$MAPPING_FILTERED" \
  --removed-out "$OUTDIR/lowTPM_removed_samples.tsv" \
  --report "$REPORT_DIR/lowTPM_filter_report.tsv"
finish_step "Run check_sample.sh and synchronize low-TPM removals"

step "Standardize metadata"
TPM_STD=$(make_out_name "$TPM" "standardized")
COUNT_STD_RAW="$WORKDIR/$(basename "${COUNT_FILTERED%.csv}").standardized.raw.csv"
COUNT_STD=$(make_out_name "$COUNT" "standardized")
MAPPING_FINAL=$(make_out_name "$MAPPING_QC" "final")
python3 "$STD_SCRIPT" "$TPM_FILTERED" "$TPM_STD"
python3 "$STD_SCRIPT" "$COUNT_FILTERED" "$COUNT_STD_RAW"
# standardize_metadata_pearl_millet.py can drop rows by code; synchronize count and mapping again to the standardized TPM.
python3 "$WRAPPER_DIR/filter_and_sync_samples.py" \
  --filtered-tpm "$TPM_STD" \
  --count "$COUNT_STD_RAW" \
  --mapping-qc "$MAPPING_FILTERED" \
  --low-list /dev/null \
  --count-out "$COUNT_STD" \
  --mapping-out "$MAPPING_FINAL" \
  --removed-out "$WORKDIR/standardization_removed_samples.tsv" \
  --report "$REPORT_DIR/standardization_sync_report.tsv"
finish_step "Standardize metadata"

step "Validate final files"
VALIDATION_REPORT="$REPORT_DIR/validate_final_report.json"
python3 "$WRAPPER_DIR/validate_gexa_update.py" \
  --count "$COUNT_STD" \
  --tpm "$TPM_STD" \
  --mapping-qc "$MAPPING_FINAL" \
  --metadata-cols "$METADATA_COLS" \
  --report "$VALIDATION_REPORT"
finish_step "Validate final files"

step "Generate static shard files"
SHARD_OUT="$OUTDIR/out_sharded"
if [[ "$FORCE" -eq 1 && -d "$SHARD_OUT" ]]; then
  rm -rf "$SHARD_OUT"
fi
python3 "$PREPROCESS_SHARD_SCRIPT" "$TPM_STD" "$SHARD_OUT"
for f in meta.tsv gene_index.tsv manifest.json; do
  require_file "$SHARD_OUT/$f" "preprocess_shard.py output $f"
done
if [[ ! -d "$SHARD_OUT/shards" ]]; then
  echo "ERROR: preprocess_shard.py did not create shards directory: $SHARD_OUT/shards" >&2
  exit 1
fi
finish_step "Generate static shard files"

step "Completed"
echo "Updated count matrix:        $COUNT_UPDATED"
echo "Updated TPM matrix:          $TPM_UPDATED"
echo "Filtered count matrix:       $COUNT_FILTERED"
echo "Filtered TPM matrix:         $TPM_FILTERED"
echo "Final standardized count:    $COUNT_STD"
echo "Final standardized TPM:      $TPM_STD"
echo "Final mapping QC:            $MAPPING_FINAL"
echo "Shard directory:             $SHARD_OUT"
echo "Low-TPM removed samples:     $OUTDIR/lowTPM_removed_samples.tsv"
echo "Failed samples summary:      $FAILED_SUMMARY"
echo "Reports:                     $REPORT_DIR"
echo "Log:                         $LOG"
finish_step "Completed"
